/** Canonical settings keys returned by GET/PATCH /settings */
export const SETTINGS_RESPONSE_KEYS = [
  'lastSeenVisibility',
  'onlineStatusVisibility',
  'readReceipts',
  'profileVisibility',
  'socialLinksDefaultVisibility',
  'showLastSeen',
  'pushNotifications',
  'messageNotifications',
  'mentionNotifications',
  'groupNotifications',
  'marketingNotifications',
  'emailNotifications',
  'notificationSound',
  'notificationVibration',
  'accentColor',
  'fontSize',
  'messageDensity',
  'chatWallpaper',
  'autoDownloadMedia',
  'mediaQuality',
  'saveDrafts',
  'linkPreviews',
  'typingIndicators',
  'autoCleanupDays',
  'locationVisibility',
  'discoveryVisibility',
  'showOnlineStatus',
  'updatedAt',
] as const;

export type SettingsResponseKey = (typeof SETTINGS_RESPONSE_KEYS)[number];

export const SETTINGS_DEFAULTS = {
  lastSeenVisibility: 'everyone',
  onlineStatusVisibility: 'everyone',
  readReceipts: true,
  profileVisibility: 'everyone',
  socialLinksDefaultVisibility: 'everyone',
  showLastSeen: true,
  pushNotifications: true,
  messageNotifications: true,
  mentionNotifications: true,
  groupNotifications: true,
  marketingNotifications: false,
  emailNotifications: true,
  notificationSound: true,
  notificationVibration: true,
  accentColor: 'oklch(0.55 0.2 145)',
  fontSize: 'medium',
  messageDensity: 'comfortable',
  chatWallpaper: 'default',
  autoDownloadMedia: 'wifi',
  mediaQuality: 'high',
  saveDrafts: true,
  linkPreviews: true,
  typingIndicators: true,
  autoCleanupDays: 30,
  locationVisibility: 'approximate',
  discoveryVisibility: 'everyone',
  showOnlineStatus: true,
} as const;
